---
title: "Species redistribution - Get predictor variables for use in SDMs"
author: "Brunno F Oliveira"
date: Sys.Date()
output:   
  html_document:
    toc: true
    toc_float: true
    code_folding: hide 
---

# Download 
Data from Copernicus (https://resources.marine.copernicus.eu/product-detail/GLOBAL_MULTIYEAR_BGC_001_029/INFORMATION)

Variables of interest are: 
* Ph *
* Oxigen *
* Primary productivity *

DO NOT PARALLELIZE THIS WORK! YOU ARE LIMITED BY NETWORK SPEED. IF PARALLELIZING YOU END UP WITH A LOT OF SLOW DOWNLOADS.

RUN THIS IN ROSSINANTE

# Setup
```{r eval=FALSE}

rm(list=ls())
gc()

list.of.packages <- c("RCurl","curl", "raster", "ncdf4", "satin", "pbapply", "parallel",
                      "sqldf","RSQLite","jsonlite")

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]

if(length(new.packages)) install.packages(new.packages)

sapply(list.of.packages, require, character.only = TRUE)

```

# Load functions
```{r}

source(here::here("R/my_functions.R"))

```

# Download CMEMS
```{r}
user = Sys.getenv("CMEMS_USER")
password = Sys.getenv("CMEMS_PWD")

# Download ph and o2
years = as.character(1993:2020)
months <- sprintf("%02d", 1:12)
nc_path <- "/media/seagate/boliveira/Marine"
variables <- c("ph", "o2")
depths = 1

for(i in 1:length(variables)){
    GetCopernicusCMEMS(user = user, 
                       password = password, 
                       nc_path = here::here(nc_path,variables[i]), 
                       years = years, 
                       months = months, 
                       variables = variables[i],
                       keep.original = FALSE,
                       over.write = FALSE)
}



```

# Save model raster
To be used for extracting cell ID
```{r}

# Get a temporary raster with a 0.25 resolution (as in CMEMS) for transforming SST rasters (from 0.05 resolution)
model.raster <- list.files(here::here(nc_path,"ph"), full.names = TRUE)[1]
model.raster <- rast(model.raster)

m <- c(minmax(model.raster), 1)
rclmat <- matrix(m, ncol=3, byrow=TRUE)
rc1 <- terra::classify(model.raster, rclmat, othersNA = TRUE)

writeRaster(rc1, 
            here::here(nc_path,"model_raster_mar.tif"), 
            overwrite = TRUE)

```

# Download SST
```{r}

years = as.character(1993:2020)
months <- sprintf("%02d", 1:12)
nc_path <- "/media/seagate/boliveira/Marine/SST"

GetCopernicusSST(user = user, 
                 password = password, 
                 nc_path = nc_path, 
                 years = years, 
                 months = months, 
                 model.raster = model.raster)

# test if everything has been downloaded
# Files should look  like this 
myfiles <- seq.Date(from = as.Date("1993/01/01"), to = as.Date("2020/12/01"), by = "month")
myfiles <- format(myfiles, "%Y%m")
myfiles <- paste0("SST_",myfiles)
# N downloaded files
mydowns <- list.files(nc_path, pattern = "*.tif")
mydowns <- gsub(".tif","",mydowns)
# test
all(myfiles %in% mydowns)
length(myfiles) == length(mydowns)

```


