---
title: "Species redistribution - Get predictor variables for use in SDMs"
author: "Brunno F Oliveira"
date: Sys.Date()
output:   
  html_document:
    toc: true
    toc_float: true
    code_folding: hide 
---

# Download 
Data from Copernicus (https://resources.marine.copernicus.eu/product-detail/GLOBAL_MULTIYEAR_BGC_001_029/INFORMATION)

Variables of interest is SST

DO NOT PARALLELIZE THIS WORK! YOU ARE LIMITED BY NETWORK SPEED. IF PARALLELIZING YOU END UP WITH A LOT OF SLOW DOWNLOADS.

RUN THIS IN ROSSINANTE

# Setup
```{r eval=FALSE}

rm(list=ls())
gc()

list.of.packages <- c("RCurl","curl", "raster", "terra", "ncdf4", "satin", "pbapply", "parallel","sf",
                      "sqldf","RSQLite","jsonlite")

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]

if(length(new.packages)) install.packages(new.packages)

sapply(list.of.packages, require, character.only = TRUE)

```

# Load functions and provide arguments
```{r}

source(here::here("R/my_functions.R"))

user = Sys.getenv("CMEMS_USER")
password = Sys.getenv("CMEMS_PWD")

```

# Download SST
```{r}

# years = as.character(1993:2020)
years = as.character(1982:2021)
months <- sprintf("%02d", 1:12)
nc_path <- "/media/seagate/boliveira/Marine/SST"

GetCopernicusSST(user = user, 
                 password = password, 
                 nc_path = nc_path, 
                 years = years, 
                 months = months, 
                 model.raster = NULL,
                 check_if_file_exists = TRUE)

# test if everything has been downloaded
# Files should look  like this 
myfiles <- seq.Date(from = as.Date(paste(min(years),"01","01",sep = "/")), 
                    to = as.Date(paste(max(years),"01","01",sep = "/")), 
                    by = "month")
myfiles <- format(myfiles, "%Y_%m")
myfiles <- paste0("SST_",myfiles)
# N downloaded files
mydowns <- list.files(nc_path, pattern = "*.tif")
mydowns <- gsub(".tif","",mydowns)
# test
all(myfiles %in% mydowns)
length(myfiles) == length(mydowns)

```

# Save model raster
To be used for extracting cell ID
```{r}

tmp <- list.files(nc_path)[1]
tmp <- rast(here::here(nc_path,tmp))

tmp <- is.na(tmp)
tmp <- ifel(tmp,0,1)
names(tmp) <- "model_raster_mar"

writeRaster(tmp, here::here("/media/seagate/boliveira/Marine/model_raster_mar.tif"), overwrite = TRUE)

```


# Make tiles
Divide the world in 10 pieces
```{r}

nc_path <- "/media/seagate/boliveira/Marine/SST"
n_tiles = 10

library(randomcoloR)

tmp <- rast(list.files(here::here(nc_path),full.names = TRUE)[1])
wrld <- rnaturalearth::ne_coastline(scale = 110, returnclass = c("sp", "sf"))
# plot(wrld)

# remove Antarctica
myext <- ext(tmp)
myext[3] <- -60
wrld <- terra::crop(vect(wrld), myext)
# plot(wrld)

# create tiles
tiles <- rast(nrow = 2, ncol = 5, myext)
tiles[1:ncell(tiles)] <- 1:ncell(tiles)
plot(tiles,col=distinctColorPalette(100));plot(wrld,add=T)

# remove tiles that falls completely in the ocean
tiles <- terra::mask(tiles,wrld)
plot(tiles,col=distinctColorPalette(100));plot(wrld,add=T)

# write tiles to disk
if(!dir.exists(here::here(nc_path,"Tiles"))){
    dir.create(here::here(nc_path,"Tiles"))
}

files <- list.files(here::here(nc_path),full.names = TRUE,pattern = ".tif")
files_names <- list.files(here::here(nc_path),pattern = ".tif")
files_names <- sapply(files_names, gsub, pattern = ".tif", replacement = "")

mclapply(1:length(files), function(i){
    tmp1 <- rast(files[i])
    tmp_name <- files_names[i]
    makeTiles(tmp1, tiles, here::here(nc_path,"Tiles",paste0(tmp_name,"_tile.tif")),overwrite=TRUE)
}, mc.cores = 40)

```

